### ISSUE TITLE
Eureka connection with Gateway isn't correctly displaying

### ISSUE THREAD

**Issue by hhjfdkl** [DustinYansberg/ProjectThree-BackEnd#11]

**Comment by hhjfdkl** [comment]
Eureka's landing page doesn't properly show the ms-gateway link. It displays a link that takes you to http://ms-gateway-5dc446dd5c-g8jxt:9001/actuator/info which isn't an active link (can't connect to server at ms-gateway-5dc446dd5c-g8jxt)

Unsure if it's an issue with the Kubernetes deployment of the ms-gateway image or if it's something else.

The deployed Eureka's link displayed properly when I connected with my local version of ms-gateway, and also properly displayed when both were hosted locally on my machine.

**Comment by DustinYansberg** [comment]
The likely culprit is how the service is telling eureka it wants to be identified.


A portion of the `application.yml` file for ms-gateway reads as follows:

```
eureka:
  client:
    service-url:
      defaultZone: http://<some-ip-of-eureka>:8761/eureka # Default value for eureka 
```

Eureka doesn't know exactly what name to give the service-url of the service so it defaults to whatever hostName the service has. In this case, the hostname of the service is `ms-gateway-5dc446dd5c-g8jxt` 

by telling Eureka to instead use the IP address this should fix the issue. We can do that by altering the above snippet to look like this:

```
eureka:
  client:
    service-url:
      defaultZone: http://<some-ip-of-eureka>:8761/eureka # Default value for eureka 
  instance:
    prefer-ip-address: true
```

We'll try this fix and then see if things work as intended.

**Comment by hhjfdkl** [comment]
Local IP is what we get from prefer-ip-address. Will continue tomorrow

**Comment by DustinYansberg** [comment]
the external ip address can be hardcoded into the application.yml file, but that is not ideal. If we did that, we would have to deploy it first to get the IP, then update the application.yml file, then redeploy it. Will pick back up tomorrow.

**Comment by DustinYansberg** [comment]
for the k8s deployment yaml file I need to add the external ip address to the environment variables of the deployment

this can be done by appending an env declaration to the containers section of the deployment yaml.

It should look like this:
```
        env:
        - name: EXTERNAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

then in the `application.yml` file of ms-gateway, that environment variable needs to be referenced like this:

```
  instance:
    prefer-ip-address: true
    ip-address: ${EXTERNAL_IP}
```

Will try this solution out tomorrow.
